### ISSUE TITLE
Large files not seen over FTP

### ISSUE THREAD

**Issue by zappepappe** [Ryzee119/LithiumX#16]
Files 2GB and larger aren't seen when viewing from a FTP client (FileZilla). While you can transfer files close to 4GB, as soon as they are done they become invisible on the client side.

**Comment by Ryzee119** [comment]
oops thanks for reporting. Fixed by https://github.com/Ryzee119/LithiumX/commit/ad38ace1bf94e498a8b4de880a16393c45ad26fd
Will publish v0.9 shortly
