### ISSUE TITLE
Recents page works only when executable is named default.xbe

### ISSUE THREAD

**Issue by amak79** [Ryzee119/LithiumX#17]
I launched UnleashX via the XBE browser and when returning to LithiumX there was an entry in the Recent page for UnleashX. When I tried to launch UnleashX via the Recent page I got a quick loading screen and was then returned back to LithiumX.

UnleashX was installed by OGXBox Installer 2021 1.5.4 and the executable was named `unleashx.xbe`. If I rename the UnleashX executable to `default.xbe` I can then launch it via the Recent page. I can reproduce this with other applications.

I'm not sure this is a LithiumX issue or not but I thought it may be of interest. I have a 1.4 Xbox with Cerbios 2.2.0 Beta.

**Comment by Ryzee119** [comment]
Could you please open `E:\\UDATA\\LithiumX\\recent.dat` with notepad or similar and let me know what path it has for that xbe?

**Comment by amak79** [comment]
`A:E:\Dash\UnleashX\unleashx.xbe`

**Comment by Ryzee119** [comment]
Thanks, i assume thats right? ignore the `A:`

**Comment by amak79** [comment]
Yes the path is correct.

**Comment by Ryzee119** [comment]
thanks thats narrowed it down a bit, ill look into it as soon as I can.

**Comment by Ryzee119** [comment]
I think I see the issue. Raised https://github.com/Ryzee119/LithiumX/pull/18
Couldyou please retest? Compiled binary will be https://github.com/Ryzee119/LithiumX/actions/runs/3881811133 in a few mins

Im not at the xbox at the moment so Im unable to verify.

**Comment by amak79** [comment]
It works correctly now. Thanks.

**Comment by Ryzee119** [comment]
Closed by https://github.com/Ryzee119/LithiumX/pull/18
