### ISSUE TITLE
Doesn't start on v1.6 with Stellar

### ISSUE THREAD

**Issue by chriszero** [Ryzee119/LithiumX#23]
I have LithiumX on E:\dashboard\default.xbe
On boot, it fails silently. Just a black screen forever.
Same when I start it from another dash.

Fresh install, no config-file.
No chance to debug?

**Comment by Ryzee119** [comment]
I use a 1.6 with Stellar as my main xbox.

What version of StellarOS? And PAL or NTSC?

**Comment by chriszero** [comment]
It's a PAL 1.6. But runs as NTSC (Selected "Auto") in stellar), I have installed a Stellar and a HD+.

In the meantime I found that NevolutionX have the same problem. (Nxdk problem?)  All "Old" dashboards are working. I use mainly XBMC4Gamers until now.

**Comment by Ryzee119** [comment]
Thanks for the info. What version of StellarOS?

**Comment by chriszero** [comment]
Oh, sorry. Totally forgot to mention that. Stellar is on 1.0.6

**Comment by chriszero** [comment]
Meanwhile stellar is on v1.1.2
I've tested PAL and NTSC, 480p, 720p, 1080i

Any chance to debug this?

**Comment by Ryzee119** [comment]
havent forgot about this. I just dont really know how to debug it. Im working on a big update to LithiumX at the moment and hopefully ready for testing in the next few weeks. Although Im not nore if this will be fixed.

Do  other nxdk apps work? Such as https://github.com/dracc/NevolutionX

**Comment by Ryzee119** [comment]
https://github.com/Ryzee119/LithiumX/actions/runs/5238513804

Could you try this

**Comment by chriszero** [comment]
This build works perfectly.

**Comment by Ryzee119** [comment]
Perfect, Thanks for testing. V0.9 now published.

**Comment by tankbusta** [comment]
@Ryzee119 I'm having this same issue on v0.9.1 on a 1.0 Xbox w/Stellar (v1.1.3 NTSC)
