### ISSUE TITLE
Images not loading until some key is pressed

### ISSUE THREAD

**Issue by vsilvalopes** [Ryzee119/LithiumX#27]
On the version 0.9.1 I've noticed a behavior, that none of the images load after the aplication startup.
If I touch any button on the controller (Black, White, Directional Keys, Start, Back) the game cover image loads instantly.

I'm running on :
- Xbox 1.6 
- Latest Cerbios (2.3.1)
- Games are compressed, using the Repacknator Tool
- 720p video mode.

Thanks in advance!

Screenshots atached bellow

![IMG-20230813-WA0033](https://github.com/Ryzee119/LithiumX/assets/2382580/89711134-a832-45b8-95b7-a24b5ccc0d2a)
![IMG-20230813-WA0035](https://github.com/Ryzee119/LithiumX/assets/2382580/81fb777b-b92b-4acf-9602-74e926555d17)

**Comment by Ryzee119** [comment]
I think ive fixed this with https://github.com/Ryzee119/LithiumX/commit/3d662a6739a6d3e5bde3dbb58bb832a3d322283a

Can you check the build artifact here:
https://github.com/Ryzee119/LithiumX/actions/runs/5854374242

**Comment by vsilvalopes** [comment]
Hi @Ryzee119 !

Thanks for the fast reply ! 

Tested it, and the image loading problem, is gone!

But, I've noticed an error on the Cover art scaling:

![IMG-20230814-WA0007](https://github.com/Ryzee119/LithiumX/assets/2382580/27d02171-32f6-41af-8afe-5c0fa3985a61)

When a game is not selected, a black border apears on the Left side and the botom of the space for the art : 

![Captura de tela 2023-08-14 091021](https://github.com/Ryzee119/LithiumX/assets/2382580/be7dcf5d-dea4-499c-9ebb-549cd352835e)

And when I select the game, the image resizes to the correct aspect.

**Comment by Ryzee119** [comment]
Damn made a new problem I guess. I'll check that out tomorrow

**Comment by vsilvalopes** [comment]
No problem!
Just update here and I test it!
Thanks for the work! :D

**Comment by Ryzee119** [comment]
Could you try this one?
https://github.com/Ryzee119/LithiumX/actions/runs/5876502130

**Comment by vsilvalopes** [comment]
Hi @Ryzee119 tested it, and at first everything seems ok!
The problem with the pictures is solved.

But I've got two crashes launching games, one after a Coolboot, and another after a softreset.

So I will do more testing, and report back to you!

**Comment by vsilvalopes** [comment]
Hi @Ryzee119 did some more tests, and can confirm.
Some games simply doesn't start.

So I have to power off and on the Xbox, and try again.
I'm suspecting this an issue with LithiumX, because when I try again the game works flawlessly.
And I didn't noticed this behavior using UnleashX for example.

If there's some debug that I can send you, let me know!

**Comment by vsilvalopes** [comment]
Hi @Ryzee119 did some more tests, and I think everything is fine now!

What I did was a reflash of the latest Cerbios (2.3.1) but this time using UDMA-2, instead of the UDMA-4.
Played a couple of games, changed then using softreset, and I had not a single hang on LithiumX.

So, I think that this version is indeed good!

Thanks for the support, and sorry for the confusion about Cerbios.

**Comment by Ryzee119** [comment]
Great glad its working
