### ISSUE TITLE
black screen after "mounting partitions" prompt

### ISSUE THREAD

**Issue by LukeUsher** [Ryzee119/LithiumX#33]
Running on a PAL 1.0 Xbox using the composite AV adapter; the latest commit of LithiumX boots to a black screen, however, ftp is still responsive so it doesn't seem to have actually crashed.

I experienced this issue with [8d2f35](https://github.com/Ryzee119/LithiumX/commit/38d2f354a81db7e09aaf1c3b1f0fbffbce83ce2f), compiled as per instructions in an msys environment.

The v0.9.1 release works as expected.

**Comment by Ryzee119** [comment]
Thanks for the report. Hard to see exactly why 0.9.1 works but later build don't as the only changes are trivial. 🤔

I use msys too mostly will have to compare clang/llvm versions when I get a chance

**Comment by LukeUsher** [comment]
May have just been build environment; using the `MINGW64` shell rather than the `MINGW64 CLANG` shell seems to have solved the problem, my apologies

Seems kind of counter-intuitive when the main difference between those shells is the default compiler being clang rather than mingw, but msys/mingw environments can be weird sometimes.
