### ISSUE TITLE
CPU Frequency calculation is broken over 1GHz

### ISSUE THREAD

**Issue by GXTX** [Ryzee119/LithiumX#34]
I thought it was maybe overflowing so I made the types larger and it was still doing it, so not sure.

**Comment by Ryzee119** [comment]
Fixed by https://github.com/Ryzee119/LithiumX/commit/d0fb16b71fd3ca7087fd486460182f3dca7e12e4

**Comment by Ryzee119** [comment]
![image](https://github.com/Ryzee119/LithiumX/assets/21236406/c4b8c800-2a13-4965-83a7-4cbe7f93d703)

**Comment by GXTX** [comment]
Thanks!
