### ISSUE TITLE
Fails to transfer some files from Midnight Club 3 Dub

### ISSUE THREAD

**Issue by GXTX** [Ryzee119/LithiumX#35]
![image](https://github.com/Ryzee119/LithiumX/assets/858612/2b779076-63ed-46af-ac73-ce73b77c5498)

`GetLastError()` is giving `ERROR_INVALID_NAME` or 0x7B but I can't find where this is being set?

Had the server print out some info on the files...
`ftp->parameters / ftp->path / get_win_path(ftp->path)`
```
450 abc loadscreen_career_tournament_SDCompound.xbck / /F/MC3DU/flash / F:\MC3DU\flash
226 abc bg_arcade.xbck                               / /F/MC3DU/flash / F:\MC3DU\flash
```

XBMC successfully transfers these files

**Comment by Ryzee119** [comment]
Doesnt FATX have a 42 character filename limit?
Careful with XBMC, it can silently truncate these long filenames

**Comment by GXTX** [comment]
Makes sense!
