### ISSUE TITLE
FTP adds data to end of file

### ISSUE THREAD

**Issue by zappepappe** [Ryzee119/LithiumX#38]
When transferring a larger file it kept getting corrupted. After inspection I noticed that LithiumX added 2kB at the end of the file.
The data added was taken from the last 1024kB of one transfer and the last 256kB of another.
The size of the file is 3 384 754kB.

This is the first time I've noticed any issue like this, so I don't know how to reproduce with anything other than a file of this size.

Tested with both 0.8.1 and 0.9.1. Works with XBMC.

**Comment by Ryzee119** [comment]
Thanks for the report.ill try look into it soon

**Comment by Ryzee119** [comment]
I can reproduce and I can see the issue. Should be able to fix soon

**Comment by Ryzee119** [comment]
https://github.com/Ryzee119/LithiumX/suites/16904945093/artifacts/965683278

Are you able to test this? I was able to reproduce your problem and now with this fix I first uploaded a large file, then downloaded it and compared checksums and had 100% match

**Comment by zappepappe** [comment]
I was able to transfer the file successfully with that build. Thank you.

I'll just pop in a quick question here before closing this issue. Between the 0.8.1 and 0.9.1 releases there was a transfer speed degradation of over 10%. Is this a known thing and the new normal or would it be worthy of opening another issue?

**Comment by Ryzee119** [comment]
I get about 11MB/s up and down on my network. What speeds are you seeing?

**Comment by zappepappe** [comment]
Was 11MB/s on 0.8.1. Now it's about 10MB/s or just under. Both with 0.9.1 and the test build.

**Comment by GXTX** [comment]
RE: Speeds. I'm not seeing this with master or `ftp_fix` branch.

**Comment by zappepappe** [comment]
I'm going to close this issue since it's fixed and do some testing regarding the speed issue. If I can't find anything that points to my setup I'll open a new issue about that.

Thanks for checking.
