### ISSUE TITLE
Only works in 720p

### ISSUE THREAD

**Issue by Ryzee119** [Ryzee119/LithiumX#4]
Just have it enabled for now. GPU currently crashes at the lower 720x480 resolution.
If I change the fallback to 640x480 it works , but it should work at 720x480

See https://github.com/Ryzee119/LithiumX/blob/4ef7682a298da3a1d5b644a74ae56bba36eaef7f/src/platform/xbox/platform.c#L36-L38

**Comment by Ryzee119** [comment]
I get this error
![image](https://user-images.githubusercontent.com/21236406/163947354-49d7b8b3-d348-44fe-83f9-db34e4812fb4.png)

**Comment by InternalLoss** [comment]
Loads fine as of v0.4 release :P
