### ISSUE TITLE
FTP upload speed decrease

### ISSUE THREAD

**Issue by zappepappe** [Ryzee119/LithiumX#41]
As mentioned in a previous issue. My FTP upload speed has decreased since v0.9.
I've deleted my settings, reset database, cleared cache and so on.

Ran some test to compare versions.

```
ftp_fix:
Windows ftp
4292870144 bytes sent in 444.24Seconds 9663.45Kbytes/sec.
4292870144 bytes sent in 447.93Seconds 9583.71Kbytes/sec.
4292870144 bytes sent in 448.50Seconds 9571.64Kbytes/sec.
FileZilla ~10MB/s

0.8.1:
Windows ftp
4292870144 bytes sent in 402.25Seconds 10672.06Kbytes/sec.
4292870144 bytes sent in 404.66Seconds 10608.51Kbytes/sec.
4292870144 bytes sent in 404.04Seconds 10625.00Kbytes/sec.
FileZilla ~11MB/s

0.9:
Windows ftp
4292870144 bytes sent in 444.18Seconds 9664.69Kbytes/sec.
4292870144 bytes sent in 452.50Seconds 9487.03Kbytes/sec.
4292870144 bytes sent in 444.16Seconds 9665.23Kbytes/sec.
FileZilla ~10MB/s

0.9.1:
Windows ftp
4292870144 bytes sent in 443.03Seconds 9689.75Kbytes/sec.
4292870144 bytes sent in 444.73Seconds 9652.73Kbytes/sec.
4292870144 bytes sent in 444.66Seconds 9654.32Kbytes/sec.
FileZilla ~10MB/s
```

**Comment by GXTX** [comment]
With current master (27f5b19) `Status:	File transfer successful, transferred 4,290,733,056 bytes in 365 seconds`, ~11.76MB/s.

**Comment by zappepappe** [comment]
May I ask what client you are using to make that transfer?

Also, I'm trying to build 0.8.1 with MSYS2 but for whatever reason it fails, newer versions build fine, any idea what it might be?

**Comment by GXTX** [comment]
FileZilla

**Comment by Ryzee119** [comment]
@zappepappe what error when building?

**Comment by zappepappe** [comment]
Took a look again. So what I did was cloned nxdk and activate it. Then I cloned LithiumX, checked out v0.8.1 and activated nxdk in ./src/libs. Tried building, but it seems like it is looking for lvgl in ./src/lib, not libs.

**Comment by GXTX** [comment]
```
git clone --recursive https://github.com/Ryzee119/LithiumX
cd LithiumX
./src/libs/nxdk/bin/activate
make -f Makefile.nxdk -j8
```

You don't really need to be manually building anyway, you can download build artifacts in the `Actions` tab.

**Comment by zappepappe** [comment]
That will build master, which I said I had no issues with.
My idea was to do a bisect to see at what commit I lost speed. As far as I can tell you don't keep artifacts that old.

**Comment by GXTX** [comment]
Then you just need to to `git checkout <buildhash>` and make sure you reset the modules when you checkout.

**Comment by zappepappe** [comment]
I tried doing that with `git checkout --recurse-submodules v0.8.1`, but that still didn't work. Went nuclear and made a new clone straight to branch v0.8.1, which seem to have given me all the right sub modules, but it still wouldn't build.
And I couldn't easily see what went wrong. (Not a coder but I tend to be able to get things to compile)

**Comment by zappepappe** [comment]
> @zappepappe what error when building?

This seems to be the error that later lead to the build stopping when trying to build v0.8.1.
```
C:/msys64/home/Zarper/LithiumX/src/lib/nxdk/lib/pdclib/platform/xbox/functions/assert/assert.c:12:5: error: call to
      undeclared function 'snprintf'; ISO C99 and later do not support implicit function declarations
      [-Wimplicit-function-declaration]
   12 |     snprintf(buffer, 512, "In function '%s': ", function_name);
      |     ^
C:/msys64/home/Zarper/LithiumX/src/lib/nxdk/lib/pdclib/platform/xbox/functions/assert/assert.c:12:5: note: did you
      mean '_snwprintf'?
C:/msys64/home/Zarper/LithiumX/src/lib/nxdk/lib/xboxrt/libc_extensions/wchar_ext_.h:10:5: note: '_snwprintf' declared
      here
   10 | int _snwprintf(wchar_t *buffer, size_t count, const wchar_t *format, ...);
      |     ^
1 warning and 1 error generated.
2 warnings generated.
```

**Comment by delacor** [comment]
Build with the flag `-Wimplicit-function-declaration`

**Comment by Ryzee119** [comment]
Please retry with v0.9.6, open a new issue if still present.
