### ISSUE TITLE
Folder Depth

### ISSUE THREAD

**Issue by jamesah2008** [Ryzee119/LithiumX#50]
I'm attempting to add a large CCI collection to my lithiumX.toml file but the default dash doesn't seem to do a deep enough scan of the folder structure to see the XBE files. Any suggestions? 

Example:
F:/Games/USA/Halo2/default.xbe (with accompanying cci)

Also it would be nice to have scrolling inside the XBE launcher. Getting down to games deep into the alphabet manually is tough.

**Comment by jamesah2008** [comment]
Also changing the games directory on the .toml file incorrectly results in an inaccessible dashboard. I have to pull my hard drive because it's just black screening instead of falling back to an alternate dash. Not a big deal since the machine is already torn apart.

**Comment by Ryzee119** [comment]
I doesn't do recursive scanning for performance reasons. You'll need to add `f:/games/usa` as the folder path
 That should work

Scrolling in the xbe browser is a good idea. I'll look into it

Also thanks for reporting that issue with the toml. I'll see why it's doing that.

**Comment by Ryzee119** [comment]
>Also it would be nice to have scrolling inside the XBE launcher

This is now in v0.9.6
