### ISSUE TITLE
No games

### ISSUE THREAD

**Issue by pkerga** [Ryzee119/LithiumX#52]
I've managed to boot 🙂
Games work with xbmc4gamers. 
Games folders are in a folder named "F:/Jeux"
I've modified lithiumx.toml
No games shown in LithiumX.
I've renamed the games folders as "Games", i've tried to put it in E. Not better.
Apps in E:/Apps are here. 
I've got an 1.4 Xbox. 
Thanks for

**Comment by Ryzee119** [comment]
There's an option in the menu to rebuild the data base on next boot. Try that
