### ISSUE TITLE
Building on linux.

### ISSUE THREAD

**Issue by samiscool51** [Ryzee119/LithiumX#53]
for those intrested in building the linux version, these are the commands i used to build it on debian 12:
```
sudo apt install pkgconf libsdl2-dev libturbojpeg0-dev libjpeg-dev
mkdir build && cd build
cmake .. -G "Unix Makefiles"
cmake --build .
```
builds perfectly fine on my system, hope this helps someone.
![image](https://github.com/Ryzee119/LithiumX/assets/13957636/6f8394ef-e4b9-421a-b0ac-bb4aac1a5906)

**Comment by Ryzee119** [comment]
Can you please raise a PR to include on the main README
