### ISSUE TITLE
UI feels large

### ISSUE THREAD

**Issue by InternalLoss** [Ryzee119/LithiumX#6]
While the UI features are really nice, the fact it covers the entire screen makes it feel a bit clunky - this could be a matter of personal taste, but it'd be nice for it to be more central :)

**Comment by Ryzee119** [comment]
I assume this is in 640x480?
Its generally recommended to use 720p, but I can look at improving this a bit. I feel the same

**Comment by InternalLoss** [comment]
> I assume this is in 640x480? Its generally recommended to use 720p, but I can look at improving this a bit. I feel the same

Yes, I'm using composite still so 480i ^^

**Comment by Ryzee119** [comment]
How about something like this:
![image](https://user-images.githubusercontent.com/21236406/169924215-11d69dd0-0885-4bde-9214-d7777a45699c.png)

**Comment by Ryzee119** [comment]
Also with the new GPU accelerated backend, I can easily scale the thumbnails. I may look at adding an option to change the scale of the thumbnails. I.e this is scaled to 60% on 640x480
![image](https://user-images.githubusercontent.com/21236406/169925114-e861e457-2a68-4ea7-8fd7-b07fabae1f04.png)

**Comment by InternalLoss** [comment]
That looks a lot better! :)

**Comment by Ryzee119** [comment]
I pushed the UI size tweaks. The build artifact is here: https://github.com/Ryzee119/LithiumX/actions/runs/2374858531

If it looks ok, we can close the issue

**Comment by InternalLoss** [comment]
Looks great to me! :D
