### ISSUE TITLE
MYSYS2 - Did you mean MSYS2 

### ISSUE THREAD

**Issue by kaosengr** [Ryzee119/LithiumX#7]
in the **Build (Windows Xbox)** section of the README.md file?

and, when I try to run 

cmake .. -G "MinGW Makefiles"

I receive the following error:

CMake Error: Could not create named generator MinGW Makefiles

Generators
* Unix Makefiles               = Generates standard UNIX makefiles.
  Ninja                        = Generates build.ninja files.
  Ninja Multi-Config           = Generates build-<Config>.ninja files.
  CodeBlocks - Ninja           = Generates CodeBlocks project files.
  CodeBlocks - Unix Makefiles  = Generates CodeBlocks project files.
  CodeLite - Ninja             = Generates CodeLite project files.
  CodeLite - Unix Makefiles    = Generates CodeLite project files.
  Eclipse CDT4 - Ninja         = Generates Eclipse CDT 4.0 project files.
  Eclipse CDT4 - Unix Makefiles= Generates Eclipse CDT 4.0 project files.
  Kate - Ninja                 = Generates Kate project files.
  Kate - Unix Makefiles        = Generates Kate project files.
  Sublime Text 2 - Ninja       = Generates Sublime Text 2 project files.
  Sublime Text 2 - Unix Makefiles
                               = Generates Sublime Text 2 project files.

There is no **MinGW Makefiles** generator.  cmake version 3.22.1.

**Comment by Ryzee119** [comment]
Not sure why, just tried locally and it worked.

Ensure you have latest `mingw-w64-x86_64-cmake` and you are using the MinGW shell.

**Comment by kaosengr** [comment]
> Not sure why, just tried locally and it worked.
> 
> Ensure you have latest `mingw-w64-x86_64-cmake` and you are using the MinGW shell.

Oh, I need to start **MSYS2 MinGW 64-bit** shell, not simply **MSYS2 MSYS** when I issue the commands listed in the **Build (Windows Xbox)** section of *README.md*.

**Comment by Ryzee119** [comment]
`Build (Windows Xbox)` oops this is actually a typo. This will build a windows executable. Not an xbox executable.

If you want an xbox exec, follow the xbox instructions.

**Comment by kaosengr** [comment]
Ok, helps starting the correct build environment.  LithiumX.exe built.

README.md typos fixed.  

I'm closing this issue.
