### ISSUE TITLE
Suggestion: Move config to a TDATA folder

### ISSUE THREAD

**Issue by InternalLoss** [Ryzee119/LithiumX#8]
A big problem that we've seen in the Xbox community is dashboard is in weird places - there's no standardised place to put dashboard (other than C:/xboxdash.xbe for MS dash that some people overwrite with their custom dash), and therefore the config is up for the ride. To fix this, it may be a good idea to place config inside a TDATA folder.

The main issue here is it requires we decide on a standard code for the dashboard now, like MS' codes (IG-036 for Unreal Championship, etc) - Looking through [DBox's publisher list](https://dbox.tools/publishers/), `NX` is not in use so we could use that as an **NX**DK application but that's really your call to make and we still would have to reserve title numbers

Please let me know what you think :)

**Comment by Ryzee119** [comment]
I thought I had a reason to put it next to the xbe but I cant remember now, it may have been for testing and I forgot to change it :) so I am keen to change that.

I currently use UDATA to store a list of recently played titles, but not sure if TDATA or UDATA is better?

In UDATA I create "UDATA/LithiumX/TitleMeta.xbx" so it appears in the dash save files so can be deleted if needed.

**Comment by InternalLoss** [comment]
UDATA I believe shows up in the dash save files, I feel that TDATA might be more suited for info like a config (versus recently played titles?) but I could be wrong, and I think DLC shows up anyway in TDATA so it's a weird one on which to pick

Didn't realise you could use full names in the UDATA(/TDATA) folders, in which case my second point is completely moot 😅

**Comment by Ryzee119** [comment]
I am going to keep in UDATA, I assume this stands for (User)DATA? as opposed to (Title?)DATA plus we can delete in MSDash memory manager which is what I want.

Thanks for the info though
